spring:
  application:
    name: secAI-container-engine
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/secAI_container_engine
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379

#knife4j:
#  enable: true
#  openapi:
#    title: "接口文档"
#    version: v1.0
#    group:
#      default:
#        api-rule: package
#        api-rule-resources:
#          - com.example.secaicontainerengine.controller

logging:
  level:
    root: info